name: uppercase_example

queues:
  - name: q1
    capacity: 128

  - name: q2
    capacity: 128

stages:
  - name: source
    type: noop_source
    threads: 1
    output_queue: q1

  - name: upper
    type: uppercase_transform
    threads: 1
    input_queue: q1
    output_queue: q2

  - name: sink
    type: stdout_sink
    threads: 1
    input_queue: q2
