queues:
  # source → uppercase
  - name: q_in
    type: QUEUE_TYPE_MPMC
    capacity: 256

  # uppercase → sink
  - name: q_out
    type: QUEUE_TYPE_MPSC
    capacity: 256

stages:
  - name: source
    type: noop_source
    threads: 1
    output_queue: q_in
    config:
      delay_ms: 100
      message: "uppercase test"
      max_messages: 20

  - name: uppercase
    type: uppercase_transform
    threads: 1
    input_queue: q_in
    output_queue: q_out

  - name: sink
    type: stdout_sink
    threads: 1
    input_queue: q_out
